// Generated by gencpp from file servo_publisher/servo_attachResponse.msg
// DO NOT EDIT!


#ifndef SERVO_PUBLISHER_MESSAGE_SERVO_ATTACHRESPONSE_H
#define SERVO_PUBLISHER_MESSAGE_SERVO_ATTACHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_publisher
{
template <class ContainerAllocator>
struct servo_attachResponse_
{
  typedef servo_attachResponse_<ContainerAllocator> Type;

  servo_attachResponse_()
    : done()  {
    }
  servo_attachResponse_(const ContainerAllocator& _alloc)
    : done(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::servo_publisher::servo_attachResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_publisher::servo_attachResponse_<ContainerAllocator> const> ConstPtr;

}; // struct servo_attachResponse_

typedef ::servo_publisher::servo_attachResponse_<std::allocator<void> > servo_attachResponse;

typedef boost::shared_ptr< ::servo_publisher::servo_attachResponse > servo_attachResponsePtr;
typedef boost::shared_ptr< ::servo_publisher::servo_attachResponse const> servo_attachResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_publisher::servo_attachResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_publisher::servo_attachResponse_<ContainerAllocator1> & lhs, const ::servo_publisher::servo_attachResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_publisher::servo_attachResponse_<ContainerAllocator1> & lhs, const ::servo_publisher::servo_attachResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_publisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_publisher::servo_attachResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_publisher::servo_attachResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_publisher::servo_attachResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6f8833c91017f802acaa131839007d";
  }

  static const char* value(const ::servo_publisher::servo_attachResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6f8833c91017f8ULL;
  static const uint64_t static_value2 = 0x02acaa131839007dULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_publisher/servo_attachResponse";
  }

  static const char* value(const ::servo_publisher::servo_attachResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string done\n"
;
  }

  static const char* value(const ::servo_publisher::servo_attachResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_attachResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_publisher::servo_attachResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_publisher::servo_attachResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_PUBLISHER_MESSAGE_SERVO_ATTACHRESPONSE_H
